name: Build, test and Publish
on:
  push:
    branches:
    - master

jobs:
  build:      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        registry-url: 'https://npm.pkg.github.com'      
    - run: | 
          yarn install
          yarn test 
          yarn build
          yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
       